"""add_fileupload_model

Revision ID: 01b4d1ddc1d1
Revises: c72b11cbb0e6
Create Date: 2026-03-17 20:36:52.673179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b4d1ddc1d1'
down_revision: Union[str, None] = 'c72b11cbb0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('report_id', sa.UUID(), nullable=False, comment='İlişkili rapor'),
    sa.Column('uploaded_by', sa.UUID(), nullable=True, comment='Dosyayı yükleyen kullanıcı'),
    sa.Column('original_name', sa.String(length=255), nullable=False, comment='Örn: sunum.pdf'),
    sa.Column('storage_key', sa.String(length=500), nullable=False, comment='MinIO bucket içindeki eşsiz path'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='Dosya boyutu (byte)'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME tipi (örn. application/pdf)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Benzersiz kayıt kimliği (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Kayıt oluşturma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Son güncelleme tarihi'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete: True=aktif, False=silinmiş'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_is_active'), 'files', ['is_active'], unique=False)
    op.create_index(op.f('ix_files_report_id'), 'files', ['report_id'], unique=False)
    op.create_index(op.f('ix_files_storage_key'), 'files', ['storage_key'], unique=True)
    op.create_index(op.f('ix_files_uploaded_by'), 'files', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_uploaded_by'), table_name='files')
    op.drop_index(op.f('ix_files_storage_key'), table_name='files')
    op.drop_index(op.f('ix_files_report_id'), table_name='files')
    op.drop_index(op.f('ix_files_is_active'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
