"""add require_youtube and require_file to courses

Revision ID: 1800d5eb63df
Revises: 01b4d1ddc1d1
Create Date: 2026-04-04 23:00:32.945094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1800d5eb63df'
down_revision: Union[str, None] = '01b4d1ddc1d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('require_youtube', sa.Boolean(), server_default='false', nullable=False, comment='Haftalık raporda YouTube video zorunlu mu'))
    op.add_column('courses', sa.Column('require_file', sa.Boolean(), server_default='false', nullable=False, comment='Haftalık raporda dosya ekleme zorunlu mu'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'require_file')
    op.drop_column('courses', 'require_youtube')
    # ### end Alembic commands ###
