"""initial_tables

Revision ID: 60b832ad0e78
Revises: 
Create Date: 2026-03-14 15:16:54.307774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60b832ad0e78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Okul mail adresi (unique)'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt ile hashlenmiş şifre'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Ad soyad'),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='user_role'), nullable=False, comment='Kullanıcı rolü: student, teacher, admin'),
    sa.Column('department', sa.String(length=200), nullable=True, comment='Bölüm adı'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Benzersiz kayıt kimliği (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Kayıt oluşturma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Son güncelleme tarihi'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete: True=aktif, False=silinmiş'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('projects',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Proje başlığı'),
    sa.Column('description', sa.Text(), nullable=False, comment='Proje açıklaması'),
    sa.Column('course_id', sa.UUID(), nullable=True, comment="Ders ID'si (Faz 2)"),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', 'IN_PROGRESS', 'COMPLETED', name='project_status'), nullable=False, comment='Proje durumu'),
    sa.Column('created_by', sa.UUID(), nullable=False, comment='Projeyi oluşturan kullanıcı'),
    sa.Column('ai_task_plan', sa.JSON(), nullable=True, comment='AI önerisi (görev planı)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Benzersiz kayıt kimliği (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Kayıt oluşturma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Son güncelleme tarihi'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete: True=aktif, False=silinmiş'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_course_id'), 'projects', ['course_id'], unique=False)
    op.create_index(op.f('ix_projects_created_by'), 'projects', ['created_by'], unique=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_is_active'), 'projects', ['is_active'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('project_members',
    sa.Column('project_id', sa.UUID(), nullable=False, comment="Proje ID'si"),
    sa.Column('user_id', sa.UUID(), nullable=False, comment="Üye kullanıcı ID'si"),
    sa.Column('role', sa.String(length=50), nullable=False, comment='Proje içi rol: leader veya member'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Benzersiz kayıt kimliği (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Kayıt oluşturma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Son güncelleme tarihi'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete: True=aktif, False=silinmiş'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_member')
    )
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_index(op.f('ix_project_members_is_active'), 'project_members', ['is_active'], unique=False)
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Ait olduğu proje'),
    sa.Column('submitted_by', sa.UUID(), nullable=False, comment='Raporlayan öğrenci'),
    sa.Column('week_number', sa.Integer(), nullable=False, comment='ISO hafta numarası (1–53)'),
    sa.Column('year', sa.Integer(), nullable=False, comment='Rapor yılı'),
    sa.Column('content', sa.Text(), nullable=False, comment='Rapor içeriği'),
    sa.Column('youtube_url', sa.String(length=500), nullable=True, comment='Video rapor YouTube linki'),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REVIEWED', name='report_status'), nullable=False, comment='Rapor durumu: DRAFT → SUBMITTED → REVIEWED'),
    sa.Column('reviewer_note', sa.Text(), nullable=True, comment='Öğretmenin geri bildirimi'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Benzersiz kayıt kimliği (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Kayıt oluşturma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Son güncelleme tarihi'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete: True=aktif, False=silinmiş'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'submitted_by', 'week_number', 'year', name='uq_report_weekly')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_is_active'), 'reports', ['is_active'], unique=False)
    op.create_index(op.f('ix_reports_project_id'), 'reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_submitted_by'), 'reports', ['submitted_by'], unique=False)
    op.create_table('tasks',
    sa.Column('title', sa.String(length=200), nullable=False, comment='Görev başlığı'),
    sa.Column('description', sa.Text(), nullable=False, comment='Görev açıklaması'),
    sa.Column('project_id', sa.UUID(), nullable=False, comment='Ait olduğu proje'),
    sa.Column('assigned_to', sa.UUID(), nullable=True, comment='Görevi yapacak kullanıcı (opsiyonel)'),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'REVIEW', 'DONE', name='task_status'), nullable=False, comment='Görev durumu'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='Teslim tarihi'),
    sa.Column('ai_suggested', sa.Boolean(), nullable=False, comment='AI tarafından önerildi mi?'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Benzersiz kayıt kimliği (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Kayıt oluşturma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Son güncelleme tarihi'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete: True=aktif, False=silinmiş'),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_is_active'), 'tasks', ['is_active'], unique=False)
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_active'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_reports_submitted_by'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_project_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_is_active'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_is_active'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_active'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_created_by'), table_name='projects')
    op.drop_index(op.f('ix_projects_course_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
