"""remove approval_status and NamedBaseModel

Revision ID: 66a68fb2ca31
Revises: c4261493411a
Create Date: 2026-05-11 23:33:01.322442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66a68fb2ca31'
down_revision: Union[str, None] = 'c4261493411a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_approval_status', table_name='users')
    op.drop_column('users', 'approval_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('approval_status', postgresql.ENUM('pending', 'approved', 'rejected', name='approval_status'), server_default=sa.text("'approved'::approval_status"), autoincrement=False, nullable=False, comment='Hesap onay durumu: pending (yeni öğrenci), approved, rejected'))
    op.create_index('ix_users_approval_status', 'users', ['approval_status'], unique=False)
    # ### end Alembic commands ###
