"""add_courses_and_enrollments

Revision ID: b2339c2468a0
Revises: 60b832ad0e78
Create Date: 2026-03-14 19:19:38.956880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2339c2468a0'
down_revision: Union[str, None] = '60b832ad0e78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('name', sa.String(length=200), nullable=False, comment='Ders adı'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='Ders kodu (unique, örn: CENG314)'),
    sa.Column('semester', sa.String(length=50), nullable=False, comment='Dönem bilgisi (örn: 2025-2026 Güz)'),
    sa.Column('teacher_id', sa.UUID(), nullable=False, comment='Dersin öğretmeni'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Benzersiz kayıt kimliği (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Kayıt oluşturma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Son güncelleme tarihi'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete: True=aktif, False=silinmiş'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_is_active'), 'courses', ['is_active'], unique=False)
    op.create_index(op.f('ix_courses_teacher_id'), 'courses', ['teacher_id'], unique=False)
    op.create_table('course_enrollments',
    sa.Column('course_id', sa.UUID(), nullable=False, comment="Kurs ID'si"),
    sa.Column('student_id', sa.UUID(), nullable=False, comment="Öğrenci ID'si"),
    sa.Column('id', sa.UUID(), nullable=False, comment='Benzersiz kayıt kimliği (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Kayıt oluşturma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Son güncelleme tarihi'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete: True=aktif, False=silinmiş'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', 'student_id', name='uq_course_student')
    )
    op.create_index(op.f('ix_course_enrollments_course_id'), 'course_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_id'), 'course_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_is_active'), 'course_enrollments', ['is_active'], unique=False)
    op.create_index(op.f('ix_course_enrollments_student_id'), 'course_enrollments', ['student_id'], unique=False)
    op.alter_column('projects', 'course_id',
               existing_type=sa.UUID(),
               comment="Ders ID'si",
               existing_comment="Ders ID'si (Faz 2)",
               existing_nullable=True)
    op.create_foreign_key(None, 'projects', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'course_id',
               existing_type=sa.UUID(),
               comment="Ders ID'si (Faz 2)",
               existing_comment="Ders ID'si",
               existing_nullable=True)
    op.drop_index(op.f('ix_course_enrollments_student_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_is_active'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_id'), table_name='course_enrollments')
    op.drop_index(op.f('ix_course_enrollments_course_id'), table_name='course_enrollments')
    op.drop_table('course_enrollments')
    op.drop_index(op.f('ix_courses_teacher_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_is_active'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
