"""add_is_deleted_to_all_tables

Revision ID: c4261493411a
Revises: a1b2c3d4e5f6
Create Date: 2026-05-09 18:53:24.493759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4261493411a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_logs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_comment='Soft delete: True=aktif, False=silinmiş',
               existing_nullable=False)
    op.alter_column('activity_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('course_enrollments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_comment='Soft delete: True=aktif, False=silinmiş',
               existing_nullable=False)
    op.alter_column('course_enrollments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('courses', 'grade_level',
               existing_type=sa.VARCHAR(length=50),
               comment="Sınıf/yıl bilgisi (örn: '2. Sınıf'). Öğretmen ders açarken belirtir.",
               existing_comment="Sınıf/yıl bilgisi (örn: '2. Sınıf')",
               existing_nullable=True)
    op.alter_column('courses', 'branch',
               existing_type=sa.VARCHAR(length=50),
               comment="Şube bilgisi (örn: 'A Şubesi'). Aynı dersin birden fazla şubesini ayırt eder.",
               existing_comment="Şube bilgisi (örn: 'A Şubesi')",
               existing_nullable=True)
    op.alter_column('courses', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_comment='Soft delete: True=aktif, False=silinmiş',
               existing_nullable=False)
    op.alter_column('courses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('departments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_comment='Soft delete: True=aktif, False=silinmiş',
               existing_nullable=False)
    op.alter_column('departments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.drop_constraint('uq_departments_name', 'departments', type_='unique')
    op.alter_column('files', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_comment='Soft delete: True=aktif, False=silinmiş',
               existing_nullable=False)
    op.alter_column('files', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('notifications', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_comment='Soft delete: True=aktif, False=silinmiş',
               existing_nullable=False)
    op.alter_column('notifications', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('project_categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment="Kategori adı (ör: '2. Sınıf Projeleri')",
               existing_nullable=False)
    op.alter_column('project_categories', 'course_id',
               existing_type=sa.UUID(),
               comment='Bağlı ders — öğretmen sadece kendi dersine kategori ekleyebilir',
               existing_nullable=False)
    op.alter_column('project_categories', 'created_by',
               existing_type=sa.UUID(),
               comment='Oluşturan öğretmen veya admin',
               existing_nullable=True)
    op.alter_column('project_categories', 'color',
               existing_type=sa.VARCHAR(length=7),
               comment='UI renk etiketi (#rrggbb formatında, opsiyonel)',
               existing_nullable=True)
    op.alter_column('project_categories', 'id',
               existing_type=sa.UUID(),
               comment='Benzersiz kayıt kimliği (UUID)',
               existing_nullable=False)
    op.alter_column('project_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Kayıt oluşturma tarihi')
    op.alter_column('project_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Son güncelleme tarihi')
    op.alter_column('project_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False,
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)')
    op.alter_column('project_categories', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.create_index(op.f('ix_project_categories_id'), 'project_categories', ['id'], unique=False)
    op.create_index(op.f('ix_project_categories_is_active'), 'project_categories', ['is_active'], unique=False)
    op.alter_column('project_members', 'role',
               existing_type=postgresql.ENUM('MANAGER', 'MEMBER', name='member_role'),
               comment='Proje içi rol: MANAGER veya MEMBER',
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::member_role"))
    op.alter_column('project_members', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INVITED', 'JOIN_REQUESTED', 'REJECTED', name='member_status'),
               comment='Üyelik durumu: ACTIVE | INVITED | JOIN_REQUESTED | REJECTED',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::member_status"))
    op.alter_column('project_members', 'invited_by',
               existing_type=sa.UUID(),
               comment='Daveti gönderen yönetici (JOIN_REQUESTED için null)',
               existing_nullable=True)
    op.alter_column('project_members', 'responded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Davet/isteğin kabul veya red zamanı',
               existing_nullable=True)
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Aktif üyelik başlangıç zamanı (ACTIVE olduğunda set edilir)',
               existing_nullable=True)
    op.alter_column('project_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_comment='Soft delete: True=aktif, False=silinmiş',
               existing_nullable=False)
    op.alter_column('project_members', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('projects', 'share_code',
               existing_type=sa.VARCHAR(length=8),
               comment='Projeye katılım için paylaşılabilir kısa kod (8 karakter)',
               existing_nullable=True)
    op.alter_column('projects', 'category_id',
               existing_type=sa.UUID(),
               comment='Proje kategorisi (öğretmenin ders bazlı oluşturduğu bölüm)',
               existing_nullable=True)
    op.alter_column('projects', 'is_archived',
               existing_type=sa.BOOLEAN(),
               comment='Arşivlenmiş mi? Sadece teacher/admin arşivleyebilir',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('projects', 'archived_by',
               existing_type=sa.UUID(),
               comment='Arşivleyen kullanıcı',
               existing_nullable=True)
    op.alter_column('projects', 'archived_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Arşivlenme zamanı',
               existing_nullable=True)
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_comment='Soft delete: True=aktif, False=silinmiş',
               existing_nullable=False)
    op.alter_column('projects', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.drop_constraint('uq_project_share_code', 'projects', type_='unique')
    op.drop_index('ix_projects_share_code', table_name='projects')
    op.create_index(op.f('ix_projects_share_code'), 'projects', ['share_code'], unique=True)
    op.alter_column('reports', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_comment='Soft delete: True=aktif, False=silinmiş',
               existing_nullable=False)
    op.alter_column('reports', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('student_year_prefixes', 'prefix',
               existing_type=sa.VARCHAR(length=6),
               comment="6 haneli öğrenci no prefix'i (ör: 245235)",
               existing_nullable=False)
    op.alter_column('student_year_prefixes', 'entry_year',
               existing_type=sa.INTEGER(),
               comment='Giriş yılı (ör: 2024)',
               existing_nullable=False)
    op.alter_column('student_year_prefixes', 'label',
               existing_type=sa.VARCHAR(length=50),
               comment="Görünen sınıf etiketi (ör: '2. Sınıf')",
               existing_nullable=False)
    op.alter_column('student_year_prefixes', 'created_by',
               existing_type=sa.UUID(),
               comment='Oluşturan admin',
               existing_nullable=True)
    op.alter_column('student_year_prefixes', 'id',
               existing_type=sa.UUID(),
               comment='Benzersiz kayıt kimliği (UUID)',
               existing_nullable=False)
    op.alter_column('student_year_prefixes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Kayıt oluşturma tarihi')
    op.alter_column('student_year_prefixes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='Son güncelleme tarihi')
    op.alter_column('student_year_prefixes', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=False,
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)')
    op.alter_column('student_year_prefixes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.drop_constraint('uq_student_prefix', 'student_year_prefixes', type_='unique')
    op.drop_index('ix_student_year_prefixes_prefix', table_name='student_year_prefixes')
    op.create_index(op.f('ix_student_year_prefixes_prefix'), 'student_year_prefixes', ['prefix'], unique=True)
    op.create_index(op.f('ix_student_year_prefixes_id'), 'student_year_prefixes', ['id'], unique=False)
    op.create_index(op.f('ix_student_year_prefixes_is_active'), 'student_year_prefixes', ['is_active'], unique=False)
    op.alter_column('tasks', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_comment='Soft delete: True=aktif, False=silinmiş',
               existing_nullable=False)
    op.alter_column('tasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('user_departments', 'user_id',
               existing_type=sa.UUID(),
               comment='Kullanıcı ID (FK → users)',
               existing_comment='FK → users',
               existing_nullable=False)
    op.alter_column('user_departments', 'department_id',
               existing_type=sa.UUID(),
               comment='Bölüm ID (FK → departments)',
               existing_comment='FK → departments',
               existing_nullable=False)
    op.alter_column('user_departments', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               comment='Benzersiz kayıt kimliği (UUID)',
               existing_comment='Primary key',
               existing_nullable=False)
    op.alter_column('user_departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Kayıt oluşturma tarihi',
               existing_nullable=False)
    op.alter_column('user_departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               comment='Son güncelleme tarihi',
               existing_nullable=False)
    op.alter_column('user_departments', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_nullable=False)
    op.alter_column('user_departments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.create_index(op.f('ix_user_departments_id'), 'user_departments', ['id'], unique=False)
    op.create_index(op.f('ix_user_departments_is_active'), 'user_departments', ['is_active'], unique=False)
    op.alter_column('users', 'entry_year',
               existing_type=sa.INTEGER(),
               comment='Öğrencinin giriş yılı — prefix tablosundan kayıt anında otomatik set edilir',
               existing_nullable=True)
    op.alter_column('users', 'grade_label',
               existing_type=sa.VARCHAR(length=50),
               comment="Sınıf etiketi (ör: '2. Sınıf') — prefix tablosundan kayıt anında otomatik set edilir",
               existing_nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_comment='Soft delete: True=aktif, False=silinmiş',
               existing_nullable=False)
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete: True=aktif, False=silinmiş',
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_nullable=False)
    op.alter_column('users', 'grade_label',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Sınıf etiketi (ör: '2. Sınıf') — prefix tablosundan kayıt anında otomatik set edilir",
               existing_nullable=True)
    op.alter_column('users', 'entry_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Öğrencinin giriş yılı — prefix tablosundan kayıt anında otomatik set edilir',
               existing_nullable=True)
    op.drop_index(op.f('ix_user_departments_is_active'), table_name='user_departments')
    op.drop_index(op.f('ix_user_departments_id'), table_name='user_departments')
    op.alter_column('user_departments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('user_departments', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               comment=None,
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_nullable=False)
    op.alter_column('user_departments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Son güncelleme tarihi',
               existing_nullable=False)
    op.alter_column('user_departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               comment=None,
               existing_comment='Kayıt oluşturma tarihi',
               existing_nullable=False)
    op.alter_column('user_departments', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               comment='Primary key',
               existing_comment='Benzersiz kayıt kimliği (UUID)',
               existing_nullable=False)
    op.alter_column('user_departments', 'department_id',
               existing_type=sa.UUID(),
               comment='FK → departments',
               existing_comment='Bölüm ID (FK → departments)',
               existing_nullable=False)
    op.alter_column('user_departments', 'user_id',
               existing_type=sa.UUID(),
               comment='FK → users',
               existing_comment='Kullanıcı ID (FK → users)',
               existing_nullable=False)
    op.alter_column('tasks', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('tasks', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete: True=aktif, False=silinmiş',
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_nullable=False)
    op.drop_index(op.f('ix_student_year_prefixes_is_active'), table_name='student_year_prefixes')
    op.drop_index(op.f('ix_student_year_prefixes_id'), table_name='student_year_prefixes')
    op.drop_index(op.f('ix_student_year_prefixes_prefix'), table_name='student_year_prefixes')
    op.create_index('ix_student_year_prefixes_prefix', 'student_year_prefixes', ['prefix'], unique=False)
    op.create_unique_constraint('uq_student_prefix', 'student_year_prefixes', ['prefix'])
    op.alter_column('student_year_prefixes', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('student_year_prefixes', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True,
               comment=None,
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)')
    op.alter_column('student_year_prefixes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Son güncelleme tarihi')
    op.alter_column('student_year_prefixes', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Kayıt oluşturma tarihi')
    op.alter_column('student_year_prefixes', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Benzersiz kayıt kimliği (UUID)',
               existing_nullable=False)
    op.alter_column('student_year_prefixes', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Oluşturan admin',
               existing_nullable=True)
    op.alter_column('student_year_prefixes', 'label',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment="Görünen sınıf etiketi (ör: '2. Sınıf')",
               existing_nullable=False)
    op.alter_column('student_year_prefixes', 'entry_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Giriş yılı (ör: 2024)',
               existing_nullable=False)
    op.alter_column('student_year_prefixes', 'prefix',
               existing_type=sa.VARCHAR(length=6),
               comment=None,
               existing_comment="6 haneli öğrenci no prefix'i (ör: 245235)",
               existing_nullable=False)
    op.alter_column('reports', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('reports', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete: True=aktif, False=silinmiş',
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_nullable=False)
    op.drop_index(op.f('ix_projects_share_code'), table_name='projects')
    op.create_index('ix_projects_share_code', 'projects', ['share_code'], unique=False)
    op.create_unique_constraint('uq_project_share_code', 'projects', ['share_code'])
    op.alter_column('projects', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete: True=aktif, False=silinmiş',
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_nullable=False)
    op.alter_column('projects', 'archived_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Arşivlenme zamanı',
               existing_nullable=True)
    op.alter_column('projects', 'archived_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Arşivleyen kullanıcı',
               existing_nullable=True)
    op.alter_column('projects', 'is_archived',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Arşivlenmiş mi? Sadece teacher/admin arşivleyebilir',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('projects', 'category_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Proje kategorisi (öğretmenin ders bazlı oluşturduğu bölüm)',
               existing_nullable=True)
    op.alter_column('projects', 'share_code',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='Projeye katılım için paylaşılabilir kısa kod (8 karakter)',
               existing_nullable=True)
    op.alter_column('project_members', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('project_members', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete: True=aktif, False=silinmiş',
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_nullable=False)
    op.alter_column('project_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Aktif üyelik başlangıç zamanı (ACTIVE olduğunda set edilir)',
               existing_nullable=True)
    op.alter_column('project_members', 'responded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Davet/isteğin kabul veya red zamanı',
               existing_nullable=True)
    op.alter_column('project_members', 'invited_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Daveti gönderen yönetici (JOIN_REQUESTED için null)',
               existing_nullable=True)
    op.alter_column('project_members', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INVITED', 'JOIN_REQUESTED', 'REJECTED', name='member_status'),
               comment=None,
               existing_comment='Üyelik durumu: ACTIVE | INVITED | JOIN_REQUESTED | REJECTED',
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'::member_status"))
    op.alter_column('project_members', 'role',
               existing_type=postgresql.ENUM('MANAGER', 'MEMBER', name='member_role'),
               comment=None,
               existing_comment='Proje içi rol: MANAGER veya MEMBER',
               existing_nullable=False,
               existing_server_default=sa.text("'MEMBER'::member_role"))
    op.drop_index(op.f('ix_project_categories_is_active'), table_name='project_categories')
    op.drop_index(op.f('ix_project_categories_id'), table_name='project_categories')
    op.alter_column('project_categories', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('project_categories', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=True,
               comment=None,
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)')
    op.alter_column('project_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Son güncelleme tarihi')
    op.alter_column('project_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment=None,
               existing_comment='Kayıt oluşturma tarihi')
    op.alter_column('project_categories', 'id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Benzersiz kayıt kimliği (UUID)',
               existing_nullable=False)
    op.alter_column('project_categories', 'color',
               existing_type=sa.VARCHAR(length=7),
               comment=None,
               existing_comment='UI renk etiketi (#rrggbb formatında, opsiyonel)',
               existing_nullable=True)
    op.alter_column('project_categories', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Oluşturan öğretmen veya admin',
               existing_nullable=True)
    op.alter_column('project_categories', 'course_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Bağlı ders — öğretmen sadece kendi dersine kategori ekleyebilir',
               existing_nullable=False)
    op.alter_column('project_categories', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Kategori adı (ör: '2. Sınıf Projeleri')",
               existing_nullable=False)
    op.alter_column('notifications', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('notifications', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete: True=aktif, False=silinmiş',
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_nullable=False)
    op.alter_column('files', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('files', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete: True=aktif, False=silinmiş',
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_nullable=False)
    op.create_unique_constraint('uq_departments_name', 'departments', ['name'])
    op.alter_column('departments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('departments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete: True=aktif, False=silinmiş',
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_nullable=False)
    op.alter_column('courses', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('courses', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete: True=aktif, False=silinmiş',
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_nullable=False)
    op.alter_column('courses', 'branch',
               existing_type=sa.VARCHAR(length=50),
               comment="Şube bilgisi (örn: 'A Şubesi')",
               existing_comment="Şube bilgisi (örn: 'A Şubesi'). Aynı dersin birden fazla şubesini ayırt eder.",
               existing_nullable=True)
    op.alter_column('courses', 'grade_level',
               existing_type=sa.VARCHAR(length=50),
               comment="Sınıf/yıl bilgisi (örn: '2. Sınıf')",
               existing_comment="Sınıf/yıl bilgisi (örn: '2. Sınıf'). Öğretmen ders açarken belirtir.",
               existing_nullable=True)
    op.alter_column('course_enrollments', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('course_enrollments', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete: True=aktif, False=silinmiş',
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_nullable=False)
    op.alter_column('activity_logs', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               comment=None,
               existing_comment='Soft delete: False=mevcut, True=silinmiş',
               existing_nullable=False)
    op.alter_column('activity_logs', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='Soft delete: True=aktif, False=silinmiş',
               existing_comment='Aktiflik durumu: True=aktif, False=pasif (geçici devre dışı)',
               existing_nullable=False)
    # ### end Alembic commands ###
