"""add_notification_model

Revision ID: c72b11cbb0e6
Revises: b2339c2468a0
Create Date: 2026-03-17 18:42:24.869718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c72b11cbb0e6'
down_revision: Union[str, None] = 'b2339c2468a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='Bildirimin alıcısı'),
    sa.Column('type', sa.Enum('PROJECT_APPROVED', 'PROJECT_REJECTED', 'TASK_ASSIGNED', 'REPORT_REVIEWED', 'SYSTEM_ALERT', name='notification_type'), nullable=False, comment='Bildirim tipi'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Bildirim başlığı'),
    sa.Column('message', sa.Text(), nullable=False, comment='Bildirim içeriği'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='Okundu mu?'),
    sa.Column('related_id', sa.UUID(), nullable=True, comment="İlgili nesnenin (Proje, Görev vs.) ID'si"),
    sa.Column('id', sa.UUID(), nullable=False, comment='Benzersiz kayıt kimliği (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Kayıt oluşturma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Son güncelleme tarihi'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete: True=aktif, False=silinmiş'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_active'), 'notifications', ['is_active'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_related_id'), 'notifications', ['related_id'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_related_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_active'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
