"""add_activity_logs_table

Revision ID: cdfad51fb42f
Revises: 1800d5eb63df
Create Date: 2026-04-05 16:08:34.131231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cdfad51fb42f'
down_revision: Union[str, None] = '1800d5eb63df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='İşlemi yapan kullanıcı'),
    sa.Column('action', sa.Enum('USER_LOGIN', 'USER_REGISTER', 'USER_ROLE_CHANGE', 'PROJECT_CREATE', 'PROJECT_APPROVE', 'PROJECT_REJECT', 'REPORT_SUBMIT', 'REPORT_REVIEW', 'COURSE_CREATE', 'COURSE_UPDATE', 'COURSE_DELETE', name='activity_action'), nullable=False, comment='Yapılan aksiyon'),
    sa.Column('entity_type', sa.Enum('USER', 'PROJECT', 'REPORT', 'COURSE', 'TASK', name='entity_type'), nullable=True, comment='İlgili varlık tipi'),
    sa.Column('entity_id', sa.UUID(), nullable=True, comment="İlgili varlığın ID'si"),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Ek detay bilgisi (JSON)'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='Kullanıcı IP adresi'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Benzersiz kayıt kimliği (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Kayıt oluşturma tarihi'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Son güncelleme tarihi'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete: True=aktif, False=silinmiş'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_id'), 'activity_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_entity_type'), 'activity_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_id'), 'activity_logs', ['id'], unique=False)
    op.create_index(op.f('ix_activity_logs_is_active'), 'activity_logs', ['is_active'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_is_active'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_entity_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
